# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/fpga_video_game/latest_fpga_video_game/latest_fpga_video_game.srcs/sources_1/ip/framebuffer/framebuffer.xci
# IP: The module: 'framebuffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/fpga_video_game/latest_fpga_video_game/latest_fpga_video_game.srcs/sources_1/ip/framebuffer/framebuffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'framebuffer'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: f:/fpga_video_game/latest_fpga_video_game/latest_fpga_video_game.srcs/sources_1/ip/framebuffer/framebuffer.xci
# IP: The module: 'framebuffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/fpga_video_game/latest_fpga_video_game/latest_fpga_video_game.srcs/sources_1/ip/framebuffer/framebuffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'framebuffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
